# Generated by Django 4.2.30 on 2026-07-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='chart_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='lessons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='quiz',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='stats',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='timeline',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
