# Generated by Django 4.2.30 on 2026-07-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_casestudy_chart_data_casestudy_lessons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboardentry',
            name='badge',
            field=models.CharField(choices=[('Market Rookie', 'Market Rookie'), ('Value Investor', 'Value Investor'), ('Trend Hunter', 'Trend Hunter'), ('Event Strategist', 'Event Strategist'), ('Market Legend', 'Market Legend')], default='Market Rookie', max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='badge',
            field=models.CharField(choices=[('Market Rookie', 'Market Rookie'), ('Value Investor', 'Value Investor'), ('Trend Hunter', 'Trend Hunter'), ('Event Strategist', 'Event Strategist'), ('Market Legend', 'Market Legend')], default='Market Rookie', max_length=30),
        ),
    ]
