# Generated by Django 4.2.30 on 2026-07-16 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_alter_leaderboardentry_badge_alter_userprofile_badge'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCaseStudyCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('case_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.casestudy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_study_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'case_study')},
            },
        ),
    ]
