# Generated by Django 4.2.30 on 2026-08-01 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_asset_eps_mathmodule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfAlgoMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trader_persona', models.CharField(default='Market Apprentice', max_length=100)),
                ('memory_notes', models.JSONField(blank=True, default=list)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('weaknesses', models.JSONField(blank=True, default=list)),
                ('calamities_completed', models.JSONField(blank=True, default=list)),
                ('total_story_xp', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='algo_memory', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
