# Generated by Django 4.2.30 on 2026-08-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_profalgomemory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='seen_onboarding',
            field=models.BooleanField(default=False),
        ),
    ]
